### ISSUE TITLE
Carbone-generated previews for List of Question summary

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-server#771] opened 2022-06-30 03:02 UTC
Part of Epic https://github.com/openmsupply/conforma-web-app/issues/1203

Come up with a Carbone template that can work with any template to dynamically generate a list of questions summary.

- probably only needs to show "Text" field of responses

**Comment by nmadruga** [comment] 2022-08-17 22:30
Duplicate of https://github.com/openmsupply/conforma-server/issues/772

**Closed by nmadruga** 2022-08-17 22:30 UTC
Labels: Closed: Duplicate
